nodes:
  - address: 172.31.79.254  # rancher instance'in public ip'si
    internal_address: 172.31.79.254  # rancher instance'in private ip'si
    user: ubuntu
    role: [controlplane, worker, etcd]

services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h

ssh_key_path: ~/.ssh/rancher.key

# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"